export const DOCES_QUERIDINHOS = [
  { nome: "Ovo de Páscoa",       img: "/assents/img/Categorias/Ovos.svg",                style: { width: "58px" } },
  { nome: "Morango do Amor",     img: "/assents/img/Categorias/Morango do Amor.svg",     style: { width: "38px" } },
  { nome: "Chocolate de Dubai",  img: "/assents/img/Categorias/Chocolate de Dubai.svg",  style: { width: "45px" } },
  { nome: "Bomba de Morango",    img: "/assents/img/Categorias/Bomba de Morango.svg",    style: { width: "35px" } },
  { nome: "Cake Pop",            img: "/assents/img/Categorias/Cake Pop.svg",            style: {} },
  { nome: "Brigadeiro",          img: "/assents/img/Categorias/Brigadeiro.svg",          style: {} },
  { nome: "Beijinho",            img: "/assents/img/Categorias/Beijinho.svg",            style: {} },
  { nome: "Quindim",             img: "/assents/img/Categorias/Quindim.svg",             style: {} },
  { nome: "Bolo de Pote",        img: "/assents/img/Categorias/Bolo de Pote.svg",        style: {} },
  { nome: "Brownie",             img: "/assents/img/Categorias/Brownie.svg",             style: {} },
  { nome: "Churros",             img: "/assents/img/Categorias/Churros.svg",             style: {} },
  { nome: "Açaí",                img: "/assents/img/Categorias/Acai.svg",                style: {} },
  { nome: "Donuts",              img: "/assents/img/Categorias/Donuts.svg",              style: {} },
  { nome: "Cone Recheado",       img: "/assents/img/Categorias/Cone.svg",                style: {} },
];

export const CATEGORIAS = [
  { nome: "Alfajor",            img: "/assents/img/Categorias/Alfajor.svg",            style: {} },
  { nome: "Banoffe",            img: "/assents/img/Categorias/Banoffe.svg",            style: { width: "40px" } },
  { nome: "Bolo",               img: "/assents/img/Categorias/Bolo.svg",               style: {} },
  { nome: "Bombons",            img: "/assents/img/Categorias/Bombons.svg",            style: { width: "44px" } },
  { nome: "Cheescake",          img: "/assents/img/Categorias/Cheescake.svg",          style: { width: "40px" } },
  { nome: "Cookies",            img: "/assents/img/Categorias/Cookies.svg",            style: { width: "58px" } },
  { nome: "Croissant Recheado", img: "/assents/img/Categorias/Croissant Recheado.svg", style: { width: "44px" } },
  { nome: "Cupcakes",           img: "/assents/img/Categorias/Cupcake.svg",            style: {} },
  { nome: "Donuts",             img: "/assents/img/Categorias/Donuts.svg",             style: {} },
  { nome: "Éclair",             img: "/assents/img/Categorias/Eclair.svg",             style: {} },
  { nome: "Macarons",           img: "/assents/img/Categorias/Macarons.svg",           style: {} },
  { nome: "Mousse",             img: "/assents/img/Categorias/Mousse.svg",             style: {} },
  { nome: "Palha Italiana",     img: "/assents/img/Categorias/Palha Italiana.svg",     style: {} },
  { nome: "Pavê",               img: "/assents/img/Categorias/Pave.svg",               style: { width: "38px" } },
  { nome: "Petit Gateu",        img: "/assents/img/Categorias/Petit Gateu.svg",        style: {} },
  { nome: "Pudim",              img: "/assents/img/Categorias/Pudim.svg",              style: {} },
  { nome: "Rocambole",          img: "/assents/img/Categorias/Romcabole.svg",          style: {} },
  { nome: "Sonho",              img: "/assents/img/Categorias/Sonho.svg",              style: {} },
  { nome: "Tiramisu",           img: "/assents/img/Categorias/Tiramisu.svg",           style: {} },
  { nome: "Torta",              img: "/assents/img/Categorias/Torta.svg",              style: {} },
];
